[package]
name = "jpeg2pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii85 = { version = "0.2" }
clap = { version = "4.5", features = ["derive"] }
from-to-repr = { version = "0.2", features = ["from_to_other"] }
